title: "Julian Tolbert Website"
description: "This website is for fun and explaining who I am!"
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
logo: src="Monk edit - 1.jpg"
